version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: backend-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      cms-network:
        ipv4_address: 10.0.10.3

  app:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      cms-network:
        ipv4_address: 10.0.10.2

volumes:
  postgres:
    name: backend

networks:
  cms-network:
    name: cms-network
    ipam:
      driver: default
      config:
        - subnet: '10.0.10.0/8'
